### ISSUE TITLE
@biglemonco/plop-templates fails creating a scene with Apollo data source

### ISSUE THREAD

**Issue by mikerudge** [biglemonco/modules#1]
<img width="1040" alt="Screenshot 2021-01-29 at 23 02 23" src="https://user-images.githubusercontent.com/7993324/106336112-20c73d00-6286-11eb-8dc2-2b13655546a1.png">

**Describe the bug**
Looks like there are some references that maybe broken?

**To Reproduce**
1. Choose Datasource as Apollo
2. Select all operations
3. See error

**Comment by owenr88** [comment]
This has been resolved in v0.0.6
